import type {NextPage} from 'next'
import Head from 'next/head'
import Tab from 'react-bootstrap/Tab';
import Tabs from 'react-bootstrap/Tabs';
import Navbar from "../components/template/Navbar";
import Footer from "../components/template/Footer";
import ProfileCard from "../components/ProfileCard";
import Resume from "../components/sections/Resume";
import About from "../components/sections/About";


const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Alejandro Isla | Full Stack Develop</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Navbar/>

            <main>
                <div className="container">
                    <div className="row py-0 py-md-5">
                        <div className="col-md-4">
                            <ProfileCard/>
                        </div>
                        <div className="col-md-8">
                            <div className="card">
                                <div className="card-body">
                                    <Tabs
                                        defaultActiveKey="about"
                                        id="tabs-menu"
                                        className="tabs-menu mb-3"
                                        justify
                                        // variant="pills"
                                    >
                                        <Tab eventKey="about" title="Sobre Mi">
                                            <About/>
                                        </Tab>
                                        <Tab eventKey="resume" title="Resumen">
                                            <Resume/>
                                        </Tab>
                                        <Tab eventKey="portafolio" title="Portafolio">
                                            ...
                                        </Tab>
                                        <Tab eventKey="blog" title="Blog">
                                            ...
                                        </Tab>
                                        <Tab eventKey="contact" title="Hablemos">
                                            ...
                                        </Tab>
                                    </Tabs>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>

            <Footer/>
        </div>
    )
}

export default Home
