import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import ProfileCard from '../components/ProfileCard';
import Resume from '../components/sections/Resume';
import About from '../components/sections/About';
import { useState } from 'react';
import Navigation from '../components/template/Navigation';
import Blog from '../components/sections/Blog';
import { sections } from '../data';
import { Post, Repository } from '../types';
import { Octokit } from 'octokit';
import Portfolio from '../components/sections/Portfolio';

export const getServerSideProps: GetServerSideProps = async (context) => {
    const octokit = new Octokit({
        auth: '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'
    });

    let posts: Post[] = [];
    let repos: Repository[] = [];

    try {
        await fetch('https://v1.nocodeapi.com/willywes/medium/JnQmleXbuVZgmXGD', {
            method: 'get',
            headers: [['Content-Type', 'application/json']],
            redirect: 'follow'
        })
            .then((response) => response.json())
            .then((result) => {
                posts = result as Post[];
            })
            .catch((error) => console.log('error', error));

        const { data } = await octokit.request('GET /users/{username}/repos', {
            username: 'willywes',
            type: 'owner',
            sort: 'updated',
            direction: 'desc'
        });

        repos = data as Repository[];
    } catch (e) {}

    return {
        props: {
            posts: posts,
            repositories: repos
        }
    };
};

type Props = {
    posts: Post[];
    repositories: any;
};

const Home = ({ posts, repositories }: Props) => {
    console.log(repositories);
    const [activeTab, setActiveTab] = useState('about');

    return (
        <div>
            <Head>
                <title>Alejandro Isla | Full Stack Develop</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <div className="container">
                    <div className="row py-3 py-md-5">
                        <div className="col-md-4">
                            <ProfileCard />
                        </div>
                        <div className="col-md-8">
                            <div className="card card-section">
                                <div className="card-body">
                                    <div className="row">
                                        <div className="col-12">
                                            <Navigation
                                                tabs={sections}
                                                activeTab={activeTab}
                                                setActiveTab={setActiveTab}
                                            />
                                        </div>
                                        <div className="col-12 tab-content">
                                            <div
                                                className={`${
                                                    activeTab === 'about' ? '' : 'd-none'
                                                }`}
                                            >
                                                <About />
                                            </div>
                                            <div
                                                className={`${
                                                    activeTab === 'resume' ? '' : 'd-none'
                                                }`}
                                            >
                                                <Resume />
                                            </div>
                                            <div
                                                className={`${
                                                    activeTab === 'portfolio' ? '' : 'd-none'
                                                }`}
                                            >
                                                <Portfolio repositories={repositories} />
                                            </div>
                                            <div
                                                className={`${
                                                    activeTab === 'blog' ? '' : 'd-none'
                                                }`}
                                            >
                                                <Blog posts={posts} />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    );
};

export default Home;
