import type {NextPage} from 'next'
import Head from 'next/head'
import Navbar from "../components/template/Navbar";
import Footer from "../components/template/Footer";


const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Alejandro Isla | Full Stack Develop</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Navbar />

            <main>
                <div className="container">
                    <div className="row">
                        <div className="col-12">
                            <h2 className="heading-first">Alejandro Isla.</h2>
                            <h1 className="heading-first">I build things for the web.</h1>
                        </div>
                        <div className="col-md-7 py-3">
                            <p>
                                I’m a software engineer specializing in building (and occasionally designing) exceptional digital experiences. Currently, I’m focused on building accessible, human-centered products at <a href="https://alejandroisla.cl" target="_blank" rel="noreferrer">Upstatement</a>.
                            </p>
                            <button className="btn btn-main">
                                Check my Github!
                            </button>
                        </div>
                    </div>
                </div>
            </main>

            <Footer />
        </div>
    )
}

export default Home
